@baseUrl = http://localhost:3000/api


GET {{baseUrl}}/posts

###
POST {{baseUrl}}/posts
Content-Type: application/json

{
  "destination": "Maldives5",
  "description": "Beautiful, I wanna go again asap!",
  "isBookmarked": false,
  "isArchived": false,
  "author": "test40@maildee",
  "startDate": "2022-03-23T00:00:00.000Z",
  "endDate": "2022-03-26T00:00:00.000Z"
}

###
PUT {{baseUrl}}/posts
Content-Type: application/json

{ "_id": "62388d27c63eda90e36da5cb",
  "post": {
    "destination": "Maldives",
  "description": "Beautiful, I wanna go again as soon as possible!"
  }
}

###
DELETE {{baseUrl}}/posts
Content-Type: application/json

{ "_id": "62388e78fddc73b86b9fa73e"
}