@baseUrl = http://localhost:3000/api


GET {{baseUrl}}/users

###
POST {{baseUrl}}/users
Content-Type: application/json

{ "_id": "test100@mail.de",
"userId": "6",
"fullname": "Test User"
}

###
PUT {{baseUrl}}/users
Content-Type: application/json

{ "_id": "test@2000.com",
  "user": {
  "fullname": "Test Name",
  "userId": "9sglkk1IuikfICPVPQEnH",
  "location": "Cologne"
  }
}

###
DELETE {{baseUrl}}/users
Content-Type: application/json

{ "_id": "def@abc.de"
}

