@baseUrl = http://localhost:3000/api


GET {{baseUrl}}/users

###
POST {{baseUrl}}/users
Content-Type: application/json

{ "_id": "test50@maildee",
  "fullname": "ID Test",
}

###
PUT {{baseUrl}}/users
Content-Type: application/json

{ "_id": "test50@maildee",
  "user": {
  "fullname": "Test User"
  }
}

###
DELETE {{baseUrl}}/users
Content-Type: application/json

{ "_id": "def@abc.de"
}

